CREATE TABLE alumno (
    "ID" INTEGER,
    "NOMBRE" TEXT,
    "EMAIL" TEXT,
    "DIRECCION" TEXT,
    "TELEFONO" TEXT,
    "COMENTARIO" TEXT,
    "LOCALIDAD" TEXT,
    "PROVINCIA" TEXT,
    "DNI_TUTOR" TEXT
)
